name: Marf
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19525
title: Made for the internets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#221f18'
    - '#9a6f45'
    - '#ddc293'
    - '#82abba'
  brandStrength: 0
  lightness: 0.9154653691221029
  saturation: 0.625
  rhythmicContrast: 0.38873974746093154
purpose: []
